baseURL = 'https://pilrymage.github.io/'
languageCode = 'en-us'
title = 'Ars Nova'
theme = 'sublime'
hasCJKLanguage = true
# [module]
#   [[module.imports]]
#     path = "github.com/adityatelange/hugo-PaperMod"
[markup.highlight]
  codeFences = true
[markup.goldmark.renderer]
  unsafe = true
[markup.goldmark.extensions.passthrough]
  enable = true
[markup.goldmark.extensions.passthrough.delimiters]
  block = [['\[', '\]'], ['$$', '$$']]
  inline = [['\(', '\)']]

[[menu.main]]
  name = "文章"
  url = ""
  weight = 10

[[menu.main]]
  name = "关于（英文版）"
  url = "about"
  weight = 20

[[menu.main]]
  name = "归档"
  url = "posts"
  weight = 30

[[menu.main]]
  name = "评论"
  url = "reviews"
  weight = 40

[[menu.main]]
  name = "搜索"
  url = "search"
  weight = 50

 
[params]
  math = true

  [params.features]
    search = true
    analytics = false
    seo = true
    syntaxHighlight = true
    copyCode = true

  [params.search]
    indexURL = "index.json"
    minLength = 2
    debounce = 180
    maxResults = 30

  [params.analytics]
    provider = "gtag"
    propertyID = "G-DRXDN3RP5C"
    domain = "pilrymage.github.io/blog"
    scriptURL = ""
    websiteID = ""

  [params.seo]
    defaultDescription = ""
    defaultImage = ""
    enableOpenGraph = true
    enableTwitter = true
    enableJSONLD = true

  [params.homeInfoParams]
    Title = "新艺术"
    Content = "记载个人的所见所问与发想"

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/Pilrymage"

  [[params.socialIcons]]
    name = "Telegram"
    url = "https://t.me/wugwugs"
  
  [params.fuseOpts]
    isCaseSensitive = false
    shouldSort = true
    location = 0
    distance = 1000
    threshold = 0.4
    keys = ["title", "permalink", "summary", "content"]
  
  
[caches]
  [caches.images]
    dir = ':cacheDir/images'
  
[taxonomies]
  genre = "genres"
  recommendation = "recommendations"

[outputs]
  home = ["HTML", "RSS", "JSON"]
