baseURL = 'https://pilrymage.github.io/'
languageCode = 'en-us'
title = 'pilrymage'
[module]
  [[module.imports]]
    path = "github.com/adityatelange/hugo-PaperMod"
[markup.highlight]
  codeFences = true
[markup.goldmark.renderer]
  unsafe = true
[markup.goldmark.extensions.passthrough]
  enable = true
[markup.goldmark.extensions.passthrough.delimiters]
  block = [['\[', '\]'], ['$$', '$$']]
  inline = [['\(', '\)']]

[[menu.main]]
  name = "About"
  url = "about"

[[menu.main]]
  name = "Posts"
  url = "posts"

[[menu.main]]
  name = "Review"
  url = "reviews"

[[menu.main]]
  name = "Search"
  url = "search"


[params]
  math = true

  [params.homeInfoParams]
    Title = "Paper Moon"
    Content = "ðŸ˜‡ Have a nice life..."

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/Pilrymage"

  [[params.socialIcons]]
    name = "Telegram"
    url = "https://t.me/wugwugs"
  
  [params.fuseOpts]
    isCaseSensitive = false
    shouldSort = true
    location = 0
    distance = 1000
    threshold = 0.4
    keys = ["title", "permalink", "summary", "content"]
  
  
[caches]
  [caches.images]
    dir = ':cacheDir/images'
  
[taxonomies]
  genre = "genres"
  recommendation = "recommendations"

[outputs]
  home = ["HTML", "RSS", "JSON"]